version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
      UPLOAD_DIR: ${UPLOAD_DIR}
      AI_WEBHOOK_URL: ${AI_WEBHOOK_URL}
    volumes:
      - uploads:/app/uploads
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      BACKEND_URL: ${BACKEND_URL}
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  db_data:
  uploads:
